### ISSUE TITLE
How to select row on click?

### ISSUE THREAD

**Issue by Oleg26Dev** [skclusive/Skclusive.Material.Component#5] opened 2020-03-08 08:26 UTC
How  to catch row selection on click and call my own function?
For example, 
1. user clicks on row, the row is selected and the row details displayed in other component.
2. user selects row and wants to download the object or print it etc.

Something like this is partially implemented in 
https://github.com/gustavnavar/Grid.Blazor

It is 
 <GridComponent T="Order" Grid="@_grid" OnRowClicked="@OrderDetails"></GridComponent>

I.e. on row click OrderDetail component called.

**Comment by skclusive** [comment] 2020-03-11 15:12
duplicate of #3

**Closed by skclusive** 2020-03-11 15:12 UTC
